"""Canonical built-in service and package metadata."""
PACKAGE_HINTS = {
  "yggdrasil":["yggdrasil"], "tailscale":["tailscale"],
  "zerotier":["zerotier-one"], "nebula":["nebula"], "headscale":["headscale"],
  "netbird":["netbird"], "netbird-server":[], "netmaker":[], "netclient":[],
  "i2pd":["i2pd","i2pd-git"], "i2p":["i2p"],
  "freenet":[], "hyphanet":[], "airdcpp":["airdcpp-webclient"],
  "linuxdcpp":[], "eiskaltdcpp":["eiskaltdcpp-qt"], "nicotine":["nicotine+"],
  "deluge":["deluge"], "qbittorrent":["qbittorrent"], "transmission":["transmission-gtk","transmission-cli"],
  "aria2":["aria2"], "ipfs":["kubo","ipfs"], "syncthing":["syncthing","syncthing-git"],
  "zeronet":["zeronet","zeronet-git"], "gnunet":["gnunet"], "retroshare":["retroshare-git","retroshare"]
  ,"cjdns":["cjdns"], "lokinet":["lokinet"], "veilid":["veilid","veilid-server"],
  "tahoe":[], "amule":["amule","amuled"], "slskd":["slskd-bin"],
  "soulseekqt":["soulseekqt"], "rtorrent":["rtorrent"], "tribler":["tribler-bin"],
  "fragments":["fragments"], "webtorrent":["webtorrent-cli","webtorrent-desktop"],
  "btfs":[], "opentracker":["opentracker"], "nym":[],
  "lnd":["lnd"], "monerod":["monero","monero-git"], "resilio":[]
}
AUR_INSTALL_IDS = frozenset({"airdcpp", "eiskaltdcpp", "zeronet", "gnunet", "retroshare", "lokinet", "veilid", "slskd", "soulseekqt", "tribler", "webtorrent", "opentracker", "lnd", "netbird"})
AUR_SIGNING_KEYS = {"gnunet": ("3D11063C10F98D14BD24D1470B0998EF86F59B6A",)}

DOCKER_ALIASES = {
  "yggdrasil":["yggdrasil"], "tailscale":["tailscale","tailscaled"],
  "zerotier":["zerotier","zerotier-one"], "nebula":["nebula"], "headscale":["headscale"],
  "netbird":["netbird","netbird-client"],
  "netbird-server":["netbird-server","netbird-management","netbird-signal","netbird-relay"],
  "netmaker":["netmaker","netmaker-server"], "netclient":["netclient"],
  "i2pd":["i2pd"], "i2p":["i2p-router","i2p"],
  "freenet":["freenet"], "hyphanet":["hyphanet"], "airdcpp":["airdcpp"], "nicotine":["nicotine"],
  "slskd":["slskd","soulseek"], "deluge":["deluge"], "qbittorrent":["qbittorrent"],
  "transmission":["transmission"], "aria2":["aria2"], "ipfs":["ipfs","kubo"],
  "syncthing":["syncthing"], "resilio":["resilio","resilio-sync"], "zeronet":["zeronet"],
  "gnunet":["gnunet"], "retroshare":["retroshare"], "cjdns":["cjdns"],
  "lokinet":["lokinet"], "veilid":["veilid"], "tahoe":["tahoe"], "amule":["amule"],
  "rtorrent":["rtorrent","flood","rutorrent"], "tribler":["tribler"],
  "webtorrent":["webtorrent"], "btfs":["btfs"], "opentracker":["opentracker"],
  "nym":["nym-node","nym-mixnode"], "lnd":["lnd"], "monerod":["monero","monerod"]
}
SERVICES = [
  dict(id="yggdrasil", name="Yggdrasil", icon="󰘧", category="Overlay network", commands=["yggdrasil","yggdrasilctl"], processes=["yggdrasil"], units=["yggdrasil.service"], config="/etc/yggdrasil.conf", web=""),
  dict(id="tailscale", name="Tailscale", icon="󰌷", category="Overlay network", commands=["tailscale","tailscaled"], processes=["tailscaled"], units=["tailscaled.service"], config="/etc/default/tailscaled", protectedConfig=True, web=""),
  dict(id="zerotier", name="ZeroTier", icon="󰌷", category="Overlay network", commands=["zerotier-cli","zerotier-one"], processes=["zerotier-one"], units=["zerotier-one.service"], config="/var/lib/zerotier-one/local.conf", protectedConfig=True, web=""),
  dict(id="nebula", name="Nebula", icon="󰌷", category="Overlay network", commands=["nebula","nebula-cert"], processes=["nebula"], units=["nebula.service"], config="/etc/nebula/config.yml", protectedConfig=True, web=""),
  dict(id="headscale", name="Headscale", icon="󰌷", category="Mesh control plane", commands=["headscale"], processes=["headscale"], units=["headscale.service"], config="/etc/headscale/config.yaml", protectedConfig=True, web=""),
  dict(id="netbird", name="NetBird", icon="󰌷", category="Overlay network", commands=["netbird"], processes=["netbird"], units=["netbird.service","netbird@main.service"], config="/etc/sysconfig/netbird", web=""),
  dict(id="netbird-server", name="NetBird Server", icon="󰌷", category="Mesh control plane", commands=["netbird-server"], processes=["netbird-server"], units=["netbird-server.service"], config="~/netbird/config.yaml", web=""),
  dict(id="netmaker", name="Netmaker", icon="󰌷", category="Mesh control plane", commands=["netmaker"], processes=["netmaker"], units=["netmaker.service"], config="~/netmaker/config.yaml", web=""),
  dict(id="netclient", name="Netmaker Client", icon="󰌷", category="Overlay network", commands=["netclient"], processes=["netclient"], units=["netclient.service"], config="/etc/netclient/config/netconfig", web=""),
  dict(id="i2pd", name="I2Pd", icon="󰖟", category="Anonymous network", commands=["i2pd"], processes=["i2pd"], units=["i2pd.service"], config="/etc/i2pd/i2pd.conf", web="http://127.0.0.1:7070/"),
  dict(id="i2p", name="I2P Router", icon="󰖟", category="Anonymous network", commands=["i2prouter"], processes=["i2prouter"], units=["i2prouter.service","i2p.service"], config="~/.i2p/router.config", web="http://127.0.0.1:7657/"),
  dict(id="freenet", name="Freenet", icon="󰛳", category="Anonymous network", commands=["freenet"], processes=["freenet"], units=["freenet.service"], config="/var/lib/freenet/.config/freenet/config.toml", web="http://127.0.0.1:7509/"),
  dict(id="hyphanet", name="Hyphanet", icon="󰛳", category="Anonymous network", commands=["run.sh"], processes=["wrapper"], units=["hyphanet.service"], config="~/Hyphanet/freenet.ini", web="http://127.0.0.1:8888/"),
  dict(id="airdcpp", name="AirDC++", icon="󰒍", category="Direct Connect", commands=["airdcppd","airdcpp-webclient"], processes=["airdcppd"], units=["airdcpp.service"], config="~/.airdc++", web="http://127.0.0.1:5600/"),
  dict(id="linuxdcpp", name="LinuxDC++", icon="󰒍", category="Direct Connect", commands=["linuxdcpp"], processes=["linuxdcpp"], units=[], config="~/.dc++", web=""),
  dict(id="eiskaltdcpp", name="EiskaltDC++", icon="󰒍", category="Direct Connect", commands=["eiskaltdcpp-qt","eiskaltdcpp-daemon"], processes=["eiskaltdcpp-qt","eiskaltdcpp-daemon"], units=[], config="~/.config/eiskaltdc++", web=""),
  dict(id="nicotine", name="Nicotine+", icon="󰓾", category="Soulseek", commands=["nicotine"], processes=["nicotine"], units=[], config="~/.config/nicotine", web=""),
  dict(id="deluge", name="Deluge", icon="󰇚", category="BitTorrent", commands=["deluged","deluge-gtk"], processes=["deluged","deluge-gtk"], units=["deluged.service"], config="~/.config/deluge", web="http://127.0.0.1:8112/"),
  dict(id="qbittorrent", name="qBittorrent", icon="󰇚", category="BitTorrent", commands=["qbittorrent","qbittorrent-nox"], processes=["qbittorrent","qbittorrent-nox"], units=["qbittorrent-nox.service"], config="~/.config/qBittorrent", web="http://127.0.0.1:8080/"),
  dict(id="transmission", name="Transmission", icon="󰇚", category="BitTorrent", commands=["transmission-daemon","transmission-gtk"], processes=["transmission-daemon","transmission-gtk"], units=["transmission.service","transmission-daemon.service"], config="~/.config/transmission-daemon/settings.json", web="http://127.0.0.1:9091/"),
  dict(id="aria2", name="aria2", icon="󰇚", category="Download client", commands=["aria2c"], processes=["aria2c"], units=["aria2.service"], config="~/.config/aria2/aria2.conf", web=""),
  dict(id="ipfs", name="IPFS / Kubo", icon="󰅟", category="Content network", commands=["ipfs"], processes=["ipfs"], units=["ipfs.service"], config="~/.ipfs/config", web="http://127.0.0.1:5001/webui"),
  dict(id="syncthing", name="Syncthing", icon="󰓦", category="File sync", commands=["syncthing"], processes=["syncthing"], units=["syncthing.service"], config="~/.config/syncthing/config.xml", web="http://127.0.0.1:8384/"),
  dict(id="zeronet", name="ZeroNet", icon="󰀂", category="Content network", commands=["zeronet"], processes=["zeronet","zeronet.py"], units=["zeronet.service"], config="~/.config/zeronet", web="http://127.0.0.1:43110/"),
  dict(id="gnunet", name="GNUnet", icon="󰫚", category="Anonymous network", commands=["gnunet-arm"], processes=["gnunet-service-arm"], units=["gnunet.service"], config="~/.config/gnunet.conf", web=""),
  dict(id="retroshare", name="RetroShare", icon="󰭹", category="Social network", commands=["retroshare"], processes=["retroshare"], units=[], config="~/.retroshare", web=""),
  dict(id="cjdns", name="cjdns", icon="󰘧", category="Overlay network", commands=["cjdroute"], processes=["cjdroute"], units=["cjdns.service"], config="/etc/cjdroute.conf", web=""),
  dict(id="lokinet", name="Lokinet", icon="󰒃", category="Anonymous network", commands=["lokinet"], processes=["lokinet"], units=["lokinet.service"], config="/etc/loki/lokinet.ini", protectedConfig=True, web=""),
  dict(id="veilid", name="Veilid", icon="󰦝", category="Overlay network", commands=["veilid-server","veilid-cli"], processes=["veilid-server"], units=["veilid-server.service"], config="~/.config/veilid/veilid-server.conf", web=""),
  dict(id="tahoe", name="Tahoe-LAFS", icon="󰅟", category="File storage", commands=["tahoe"], processes=["tahoe"], units=["tahoe.service"], config="~/.tahoe/tahoe.cfg", web="http://127.0.0.1:3456/"),
  dict(id="amule", name="aMule", icon="󰇚", category="eDonkey", commands=["amuled","amule"], processes=["amuled","amule"], units=["amuled.service"], config="/var/lib/amule/.aMule/amule.conf", protectedConfig=True, web="http://127.0.0.1:4711/"),
  dict(id="slskd", name="slskd", icon="󰓾", category="Soulseek", commands=["slskd"], processes=["slskd"], units=["slskd.service"], config="~/.config/slskd/slskd.yml", web="http://127.0.0.1:5030/"),
  dict(id="soulseekqt", name="SoulseekQt", icon="󰓾", category="Soulseek", commands=["SoulseekQt","soulseekqt"], processes=["SoulseekQt","soulseekqt"], units=[], config="~/.SoulseekQt", web=""),
  dict(id="rtorrent", name="rTorrent", icon="󰇚", category="BitTorrent", commands=["rtorrent"], processes=["rtorrent"], units=["rtorrent.service"], config="~/.config/rtorrent/rtorrent.rc", web=""),
  dict(id="tribler", name="Tribler", icon="󰇚", category="BitTorrent", commands=["tribler"], processes=["tribler"], units=[], config="~/.Tribler", web=""),
  dict(id="fragments", name="Fragments", icon="󰇚", category="BitTorrent", commands=["fragments"], processes=["fragments"], units=[], config="~/.var/app/de.haeckerfelix.Fragments/config", web=""),
  dict(id="webtorrent", name="WebTorrent", icon="󰇚", category="BitTorrent", commands=["webtorrent","webtorrent-desktop"], processes=["webtorrent","webtorrent-desktop"], units=[], config="~/.config/WebTorrent", web=""),
  dict(id="btfs", name="BTFS", icon="󰅟", category="File storage", commands=["btfs"], processes=["btfs"], units=["btfs.service"], config="~/.btfs/config", web="http://127.0.0.1:5001/webui"),
  dict(id="opentracker", name="opentracker", icon="󰑩", category="BitTorrent", commands=["opentracker"], processes=["opentracker"], units=["opentracker.service"], config="/etc/opentracker.conf", web=""),
  dict(id="nym", name="Nym Node", icon="󰒃", category="Anonymous network", commands=["nym-node","nym-mixnode"], processes=["nym-node","nym-mixnode"], units=["nym-node.service","nym-mixnode.service"], config="~/.nym", web=""),
  dict(id="lnd", name="Lightning Network Daemon", icon="󰢬", category="Cryptocurrency", commands=["lnd","lncli"], processes=["lnd"], units=["lnd.service"], config="~/.lnd/lnd.conf", web=""),
  dict(id="monerod", name="Monero Node", icon="󰍷", category="Cryptocurrency", commands=["monerod"], processes=["monerod"], units=["monerod.service"], config="/etc/monerod.conf", protectedConfig=True, web=""),
  dict(id="resilio", name="Resilio Sync", icon="󰓦", category="File sync", commands=["rslsync"], processes=["rslsync"], units=["resilio-sync.service"], config="~/.config/resilio-sync", web="http://127.0.0.1:8888/"),
]
