const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")
const root = path.join(__dirname, "..")
const read = name => fs.readFileSync(path.join(root, name), "utf8")
const manifest = JSON.parse(read("manifest.json"))
const bar = read("BarWidget.qml")
const settingsPanel = read("P2PSettingsPanel.qml")
const indicatorPill = read("P2PIndicatorPill.qml")
const pageNames = ["General", "Appearance", "Services", "Performance", "Discovery", "Packages"]

assert.ok(manifest.kinds.includes("service"))
assert.equal(manifest.entryPoints.service, "Service.qml")
assert.equal(manifest.keepLoaded, true)
assert.match(bar, /manageIpc:\s*false/)
assert.match(bar, /serviceFor\(moduleName\)/)
assert.doesNotMatch(bar, /id:\s*eventWatchProc/)
assert.match(bar, /Loader\s*\{\s*id:\s*settingsPageLoader/)
assert.match(bar, /active:\s*root\.showingWidgetSettings/)
assert.match(bar, /sourceComponent:\s*String\(root\.settingsSurfaceSource\)\s*===\s*""\s*\?\s*defaultSettingsSurface\s*:\s*null/)
assert.match(bar, /Component\s*\{\s*id:\s*defaultSettingsSurface;\s*P2PSettingsPanel\s*\{\s*controller:\s*root\s*\}/)
assert.match(bar, /P2PSettingsPanel \{ controller: root \}/)
assert.match(bar, /P2PServiceEditor/)
for (const name of pageNames)
  assert.match(settingsPanel, new RegExp(`P2P${name}Settings`))
assert.match(settingsPanel, /P2PSettingsNavigation/)
assert.match(indicatorPill, /HoverHandler\s*\{\s*id:\s*hoverDetector/)
assert.match(indicatorPill, /ToolTip\.visible:\s*hoverDetector\.hovered/)
assert.match(indicatorPill, /MouseArea\s*\{[\s\S]*enabled:\s*pill\.enabled/)
console.log("plugin topology contracts passed")
