const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")
const root = path.join(__dirname, "..")
const read = name => fs.readFileSync(path.join(root, name), "utf8")
const manifest = JSON.parse(read("manifest.json"))
const bar = read("BarWidget.qml")
assert.match(bar, /ColumnLayout\s*\{[\s\S]*?id:\s*popupLayout[\s\S]*?P2PHeader[\s\S]*?Flickable\s*\{[\s\S]*?id:\s*popupScroll[\s\S]*?popupLayout\.width < Style\.space\(440\)/, "the main header and footer must remain outside the scrollable content viewport")
assert.match(bar, /configuredPanelHeight:[\s\S]*?popupMaxHeight", 600[\s\S]*?contentHeight:\s*fittedContentHeight\(root\.configuredPanelHeight, root\.configuredPanelHeight\)/, "fixed chrome must retain the configured usable panel height")
assert.match(read("scripts/capture-screenshots"), /capture_panel panel[\s\S]*?audit-main\.png/, "visual audits must retain the main fixed-chrome viewport")
const settingsPanel = read("P2PSettingsPanel.qml")
assert.match(bar, /P2PSettingsNavigation[\s\S]*?Flickable\s*\{[\s\S]*?id:\s*popupScroll[\s\S]*?P2PSettingsReset/, "settings navigation and reset actions must remain outside the scroll viewport")
assert.match(bar, /popupLayout\.width < Style\.space\(440\)[\s\S]*?wrapMode:\s*Text\.WordWrap/, "the fixed main footer must use responsive copy and stay within narrow panels")
assert.doesNotMatch(settingsPanel, /P2PSettingsNavigation|P2PSettingsReset/, "the settings scroll body must contain only page content")
const indicatorPill = read("P2PIndicatorPill.qml")
const serviceCard = read("P2PServiceCard.qml")
const serviceList = read("P2PServiceList.qml")
const service = read("Service.qml")
const performanceSettings = read("P2PPerformanceSettings.qml")
const messageSurface = read("P2PMessageSurface.qml")
const pageNames = ["General", "Appearance", "Services", "Performance", "Discovery", "Packages"]

assert.equal(fs.readdirSync(root).filter(name => /^Runtime.*Test\.qml$/.test(name)).length, 0)
assert.ok(fs.readdirSync(path.join(root, "tests", "qml")).length > 0)
assert.equal(fs.readdirSync(root).filter(name => /^p2p_.*\.py$/.test(name)).length, 0)
assert.ok(fs.readdirSync(path.join(root, "backend")).some(name => /^p2p_.*\.py$/.test(name)))

assert.ok(manifest.kinds.includes("service"))
assert.equal(manifest.entryPoints.service, "Service.qml")
assert.equal(manifest.keepLoaded, true)
assert.match(bar, /manageIpc:\s*false/)
assert.match(bar, /serviceFor\(moduleName\)/)
assert.doesNotMatch(bar, /id:\s*eventWatchProc/)
assert.match(bar, /Loader\s*\{\s*id:\s*settingsPageLoader/)
assert.match(bar, /active:\s*root\.showingWidgetSettings/)
assert.match(bar, /sourceComponent:\s*String\(root\.settingsSurfaceSource\)\s*===\s*""\s*\?\s*defaultSettingsSurface\s*:\s*null/)
assert.match(bar, /Component\s*\{\s*id:\s*defaultSettingsSurface;\s*P2PSettingsPanel\s*\{\s*controller:\s*root\s*\}/)
assert.match(bar, /P2PSettingsPanel \{ controller: root \}/)
assert.match(bar, /P2PServiceEditor/)
for (const name of pageNames)
  assert.match(settingsPanel, new RegExp(`P2P${name}Settings`))
assert.match(bar, /P2PSettingsNavigation/)
assert.match(indicatorPill, /HoverHandler\s*\{\s*id:\s*hoverDetector/)
assert.match(indicatorPill, /ToolTip\.visible:\s*hoverDetector\.hovered/)
assert.doesNotMatch(indicatorPill, /enabled:\s*indicator\.enabled/)
assert.match(indicatorPill, /property bool interactive:\s*indicator\.enabled\s*!==\s*false/)
assert.match(indicatorPill, /MouseArea\s*\{[\s\S]*enabled:\s*pill\.interactive/)
assert.match(service, /P2PProcessWatchdog\s*\{\s*id:\s*settingsWatcherHandshake/)
assert.match(service, /onTimedOut:\s*root\.handleSettingsWatcherHandshakeTimeout\(\)/)
assert.match(performanceSettings, /copySupportReportButton/)
assert.match(performanceSettings, /Model\.eventJournalRows/)
assert.match(messageSurface, /signal actionRequested\(\)/)
assert.match(bar, /showSettingsSection\("performance",\s*"diagnostics"\)/)
assert.match(bar, /showSettingsSection\("discovery",\s*"custom-services"\)/)
assert.match(bar, /text === "\/"[\s\S]*serviceSearch\.forceActiveFocus\(\)/)
assert.match(bar, /consecutiveRefreshFailures > 0 \? " ~" : ""/)
assert.equal((serviceCard.match(/Model\.compactIndicators\(/g) || []).length, 1)
assert.match(serviceCard, /readonly property var compactIndicators:/)
assert.equal((serviceList.match(/groupLabelFor\(/g) || []).length, 2)
assert.match(serviceList, /readonly property string groupName:/)
assert.match(serviceList, /readonly property var gridGroups:/)
assert.match(serviceList, /objectName: "gridGroupHeader"/)
for (const name of ["serviceSortGrid", "servicePriorityGrid", "serviceGroupingGrid", "groupDisplayGrid"])
  assert.ok(read("P2PServicesSettings.qml").includes(`objectName: "${name}"`), `services settings missing ${name}`)
assert.match(read("P2PPerformanceSettings.qml"), /objectName: "refreshTriggerGrid"/)
console.log("plugin topology contracts passed")
